// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3QiL57r6t876XdblDyvS-HQMRDvKojIw',
    appId: '1:75431498431:web:5e564bc1bd36c4e915ac0a',
    messagingSenderId: '75431498431',
    projectId: 'chat-app-73283',
    authDomain: 'chat-app-73283.firebaseapp.com',
    storageBucket: 'chat-app-73283.appspot.com',
    measurementId: 'G-L0Q6C1ZG15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR66fCgJwGBweI28rNkIYmMv3QG0USn40',
    appId: '1:75431498431:android:5b8cdeaede9e1d5815ac0a',
    messagingSenderId: '75431498431',
    projectId: 'chat-app-73283',
    storageBucket: 'chat-app-73283.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBISuFXu-q6gW8EWHQ0n9CXzi7n5NNl4tU',
    appId: '1:75431498431:ios:c713ae735598c70b15ac0a',
    messagingSenderId: '75431498431',
    projectId: 'chat-app-73283',
    storageBucket: 'chat-app-73283.appspot.com',
    iosClientId: '75431498431-savgou392lc4cufa2iemj5155q8bh8us.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBISuFXu-q6gW8EWHQ0n9CXzi7n5NNl4tU',
    appId: '1:75431498431:ios:c53a746b5945605a15ac0a',
    messagingSenderId: '75431498431',
    projectId: 'chat-app-73283',
    storageBucket: 'chat-app-73283.appspot.com',
    iosClientId: '75431498431-rr71nl84c52u9hc13r8f1i76irsnrge5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
